# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all 
user1 = User.create!(email: "jshap83@icloud.com")
user2 = User.create!(email: "george@yahoo.com")
user3 = User.create!(email: "ann@yahoo.com")


ShortenedUrl.destroy_all
#user1's urls 
url1 = ShortenedUrl.shorten_url(user1, "https://www.cnn.com/2022/09/04/us/elkhorn-coral-spawn-florida-aquarium-climate/index.html")
url2 = ShortenedUrl.shorten_url(user1, "https://www.foxnews.com/lifestyle/this-labor-day-grateful-nod-long-haul-truckers-keep-america-moving")
url3 = ShortenedUrl.shorten_url(user1, "https://www.pbs.org/video/september-4-2022-pbs-news-weekend-full-episode-1662305362/")
url4 = ShortenedUrl.shorten_url(user1, "https://www.c-span.org/video/?522549-5/washington-journal-news-headlines-viewer-calls")
url5 = ShortenedUrl.shorten_url(user1, "https://www.cnbc.com/2022/09/05/economists-are-divided-on-the-risk-of-a-us-recession.html")
url6 = ShortenedUrl.shorten_url(user1, "https://abcnews.go.com/Politics/trump-acted-set-rules-apply-president-rep-michael/story?id=89269805")
url7 = ShortenedUrl.shorten_url(user1, "https://www.nbcnews.com/politics/donald-trump/trump-suggests-mar-lago-documents-bound-library-advisers-say-rarely-ta-rcna46129")
url8 = ShortenedUrl.shorten_url(user1, "https://www.cbsnews.com/news/hiring-jobs-report-august-315000-3-7/")
url9 = ShortenedUrl.shorten_url(user1, "https://www.nba.com/watch/video/how-does-trading-for-donovan-mitchell-improve-the-cavs-title-chances")
url10 = ShortenedUrl.shorten_url(user1, "https://www.bet.com/episodes/kxbzx7/haus-of-vicious-vicious-lies-season-1-ep-3")
url11 = ShortenedUrl.shorten_url(user1, "https://www.yahoo.com/finance/news/us-housing-market-returns-sanity-150000097.html")
#user2's urls
url12 = ShortenedUrl.shorten_url(user2, "https://www.cnn.com/2022/09/04/us/elkhorn-coral-spawn-florida-aquarium-climate/index.html")
url13 = ShortenedUrl.shorten_url(user2, "https://www.foxnews.com/lifestyle/this-labor-day-grateful-nod-long-haul-truckers-keep-america-moving")
url14 = ShortenedUrl.shorten_url(user2, "https://www.pbs.org/video/september-4-2022-pbs-news-weekend-full-episode-1662305362/")
url15 = ShortenedUrl.shorten_url(user2, "https://www.c-span.org/video/?522549-5/washington-journal-news-headlines-viewer-calls")
url16 = ShortenedUrl.shorten_url(user2, "https://www.cnbc.com/2022/09/05/economists-are-divided-on-the-risk-of-a-us-recession.html")
url17 = ShortenedUrl.shorten_url(user2, "https://abcnews.go.com/Politics/trump-acted-set-rules-apply-president-rep-michael/story?id=89269805")
url18 = ShortenedUrl.shorten_url(user2, "https://www.nbcnews.com/politics/donald-trump/trump-suggests-mar-lago-documents-bound-library-advisers-say-rarely-ta-rcna46129")
url19 = ShortenedUrl.shorten_url(user2, "https://www.cbsnews.com/news/hiring-jobs-report-august-315000-3-7/")
url20 = ShortenedUrl.shorten_url(user2, "https://www.nba.com/watch/video/how-does-trading-for-donovan-mitchell-improve-the-cavs-title-chances")
url21 = ShortenedUrl.shorten_url(user2, "https://www.bet.com/episodes/kxbzx7/haus-of-vicious-vicious-lies-season-1-ep-3")
url22 = ShortenedUrl.shorten_url(user2, "https://www.yahoo.com/finance/news/us-housing-market-returns-sanity-150000097.html")
#user3's urls
url23 = ShortenedUrl.shorten_url(user3, "https://www.cnn.com/2022/09/04/us/elkhorn-coral-spawn-florida-aquarium-climate/index.html")
url24 = ShortenedUrl.shorten_url(user3, "https://www.foxnews.com/lifestyle/this-labor-day-grateful-nod-long-haul-truckers-keep-america-moving")
url25 = ShortenedUrl.shorten_url(user3, "https://www.pbs.org/video/september-4-2022-pbs-news-weekend-full-episode-1662305362/")
url26 = ShortenedUrl.shorten_url(user3, "https://www.c-span.org/video/?522549-5/washington-journal-news-headlines-viewer-calls")
url27 = ShortenedUrl.shorten_url(user3, "https://www.cnbc.com/2022/09/05/economists-are-divided-on-the-risk-of-a-us-recession.html")
url28 = ShortenedUrl.shorten_url(user3, "https://abcnews.go.com/Politics/trump-acted-set-rules-apply-president-rep-michael/story?id=89269805")
url29 = ShortenedUrl.shorten_url(user3, "https://www.nbcnews.com/politics/donald-trump/trump-suggests-mar-lago-documents-bound-library-advisers-say-rarely-ta-rcna46129")
url30 = ShortenedUrl.shorten_url(user3, "https://www.cbsnews.com/news/hiring-jobs-report-august-315000-3-7/")
url31 = ShortenedUrl.shorten_url(user3, "https://www.nba.com/watch/video/how-does-trading-for-donovan-mitchell-improve-the-cavs-title-chances")
url32 = ShortenedUrl.shorten_url(user3, "https://www.bet.com/episodes/kxbzx7/haus-of-vicious-vicious-lies-season-1-ep-3")
url33 = ShortenedUrl.shorten_url(user3, "https://www.yahoo.com/finance/news/us-housing-market-returns-sanity-150000097.html")


Visit.destroy_all 
#user1's visits 
7.times { Visit.record_visit!(user1, url1) } 
Visit.record_visit!(user1, url2)
Visit.record_visit!(user1, url3)
3.times { Visit.record_visit!(user1, url4) } 
2.times { Visit.record_visit!(user1, url5) }
Visit.record_visit!(user1, url6)
Visit.record_visit!(user1, url7)
Visit.record_visit!(user1, url8)
Visit.record_visit!(user1, url9)
Visit.record_visit!(user1, url10)
Visit.record_visit!(user1, url11)
#user2's visits
Visit.record_visit!(user2, url12)
5.times { Visit.record_visit!(user2, url13) }
Visit.record_visit!(user2, url14)
Visit.record_visit!(user2, url15)
Visit.record_visit!(user2, url16)
Visit.record_visit!(user2, url17)
Visit.record_visit!(user2, url18)
Visit.record_visit!(user2, url19)
Visit.record_visit!(user2, url20)
Visit.record_visit!(user2, url21)
Visit.record_visit!(user2, url22)
#user3's visits
Visit.record_visit!(user3, url23)
Visit.record_visit!(user3, url24)
4.times { Visit.record_visit!(user3, url25) }
Visit.record_visit!(user3, url26)
Visit.record_visit!(user3, url27)
Visit.record_visit!(user3, url28)
Visit.record_visit!(user3, url29)
Visit.record_visit!(user3, url30)
Visit.record_visit!(user3, url31)
Visit.record_visit!(user3, url32)
Visit.record_visit!(user3, url33)


TagTopic.destroy_all 
tag1 = TagTopic.create!(tag_topic: "News")
tag2 = TagTopic.create!(tag_topic: "Conservative")
tag3 = TagTopic.create!(tag_topic: "Liberal")
tag4 = TagTopic.create!(tag_topic: "Public")
tag5 = TagTopic.create!(tag_topic: "Sports")
tag6 = TagTopic.create!(tag_topic: "Music")


Tagging.destroy_all 
#user1's taggings 
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url1.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url1.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url2.id)
Tagging.create!(user_id: 1, tag_topic_id: tag2.id, shortened_url_id: url2.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url3.id)
Tagging.create!(user_id: 1, tag_topic_id: tag4.id, shortened_url_id: url3.id)
Tagging.create!(user_id: 1, tag_topic_id: tag2.id, shortened_url_id: url3.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url3.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url4.id)
Tagging.create!(user_id: 1, tag_topic_id: tag4.id, shortened_url_id: url4.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url5.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url5.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url6.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url6.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url7.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url7.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url8.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url8.id)
Tagging.create!(user_id: 1, tag_topic_id: tag5.id, shortened_url_id: url9.id)
Tagging.create!(user_id: 1, tag_topic_id: tag6.id, shortened_url_id: url10.id)
Tagging.create!(user_id: 1, tag_topic_id: tag1.id, shortened_url_id: url11.id)
Tagging.create!(user_id: 1, tag_topic_id: tag2.id, shortened_url_id: url11.id)
Tagging.create!(user_id: 1, tag_topic_id: tag3.id, shortened_url_id: url11.id)
#user2's taggings 
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url12.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url12.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url13.id)
Tagging.create!(user_id: 2, tag_topic_id: tag2.id, shortened_url_id: url13.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url14.id)
Tagging.create!(user_id: 2, tag_topic_id: tag4.id, shortened_url_id: url14.id)
Tagging.create!(user_id: 2, tag_topic_id: tag2.id, shortened_url_id: url14.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url14.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url15.id)
Tagging.create!(user_id: 2, tag_topic_id: tag4.id, shortened_url_id: url15.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url16.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url16.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url17.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url17.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url18.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url18.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url19.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url19.id)
Tagging.create!(user_id: 2, tag_topic_id: tag5.id, shortened_url_id: url20.id)
Tagging.create!(user_id: 2, tag_topic_id: tag6.id, shortened_url_id: url21.id)
Tagging.create!(user_id: 2, tag_topic_id: tag1.id, shortened_url_id: url22.id)
Tagging.create!(user_id: 2, tag_topic_id: tag2.id, shortened_url_id: url22.id)
Tagging.create!(user_id: 2, tag_topic_id: tag3.id, shortened_url_id: url22.id)
#user3's taggings 
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url23.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url23.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url24.id)
Tagging.create!(user_id: 3, tag_topic_id: tag2.id, shortened_url_id: url24.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url25.id)
Tagging.create!(user_id: 3, tag_topic_id: tag4.id, shortened_url_id: url25.id)
Tagging.create!(user_id: 3, tag_topic_id: tag2.id, shortened_url_id: url25.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url25.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url26.id)
Tagging.create!(user_id: 3, tag_topic_id: tag4.id, shortened_url_id: url26.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url27.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url27.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url28.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url28.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url29.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url29.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url30.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url30.id)
Tagging.create!(user_id: 3, tag_topic_id: tag5.id, shortened_url_id: url31.id)
Tagging.create!(user_id: 3, tag_topic_id: tag6.id, shortened_url_id: url32.id)
Tagging.create!(user_id: 3, tag_topic_id: tag1.id, shortened_url_id: url33.id)
Tagging.create!(user_id: 3, tag_topic_id: tag2.id, shortened_url_id: url33.id)
Tagging.create!(user_id: 3, tag_topic_id: tag3.id, shortened_url_id: url33.id)